version: "3.9"
services:
  redis:
    build:
      context: ./services/redis
      args:
        REDIS_IMAGE: redis:${REDIS_VERSION}
    image: holovision-redis:${REDIS_VERSION}
  mysql: 
    build:
      context: ./services/mysql
      args:
        MYSQL_IMAGE: mysql:${MYSQL_VERSION}
    image: holovision-mysql:${MYSQL_VERSION}
  php82:
    build:
      context: ./services/php82
      args:
        PHP_IMAGE: ${PHP82_IMAGE}
        PHP_EXTENSIONS: redis,gd,exif
    image: holovision-php:${PHP82_VERSION}
  php83:
    build:
      context: ./services/php83
      args:
        PHP_IMAGE: ${PHP83_IMAGE}
    image: holovision-php:${PHP83_VERSION}
  nginx:
    build:
      context: ./services/nginx
      args:
        NGINX_IMAGE: nginx:${NGINX_VERSION}
    image: holovision-nginx:${NGINX_VERSION}
  node:
    build:
      context: ./services/node
      args:
        NODE_IMAGE: node:${NODE_VERSION}
    image: holovision-node:${NODE_VERSION}
  coturn:
    build:
      context: './services/coturn'
    image: holovision-coturn:1.0