version: "3.9"
services:
  redis:
    image: holovision-redis:7.2
    container_name: redis7.2
    restart: always
    privileged: false
    volumes:
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - ${DATA_DIR}/redis:/data
      - ${LOG_DIR}/redis:/logs
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - TZ:${TZ}
    command: redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    networks: 
      - ycsjnet
  mysql: 
    image: holovision-mysql:8.2
    container_name: mysql${MYSQL_VERSION}
    restart: always
    privileged: false
    volumes:
      - ${DATA_DIR}/mysql${MYSQL_VERSION}:/var/lib/mysql
      - ./conf/mysql:/docker-mysql
      - ./conf/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./logs/mysql:/var/log/mysql
      - ./conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: ${TZ}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}  通过 conf/mysql/init.sql 来创建初始化数据库
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1  --general-log=1 --general-log-file=/var/log/mysql/general.log
    networks: 
      - ycsjnet
  php82:
    image: holovision-php:8.2
    container_name: php8.2
    restart: always
    privileged: true
    volumes:
      - ${SOURCE_DIR}:/www/
      - ${CONF_DIR}/php/php.ini/:/usr/local/etc/php/php.ini
      - ${LOG_DIR}/php82:/var/log/php
      - ${ZHEGNNIAN_ROOT}:/www/zhengnian.laravel
    environment:
      - TZ:${TZ}
    depends_on:
      - redis
      - mysql
    networks: 
      - ycsjnet
  php83:
    image: holovision-php:8.3
    container_name: php8.3
    restart: always
    privileged: true
    volumes:
      - ${DABAOENSI_ROOT}:/www/dabaoensi.laravel
      - ${YILIAO_ROOT}:/www/yiliao.laravel
      - ${MARKET_ROOT}:/www/market.laravel
      - ${CONF_DIR}/php/php.ini/:/usr/local/etc/php/php.ini
      - ${LOG_DIR}/php83:/var/log/php
      - ${SOURCE_DIR}/source.17vision.com/wgk:/www/yiliao.laravel/public/wgk
      - ${SOURCE_DIR}/source.17vision.com/market:/www/market.laravel/public/market
    environment:
      - TZ:${TZ}
    # command: /bin/bash -c "service cron start && tail -f /dev/null"
    depends_on:
      - redis
      - mysql
    networks: 
      - ycsjnet
  php84:
    image: holovision-php:8.4
    container_name: php8.4
    restart: always
    privileged: true
    volumes:
      - ${PHP84_ROOT}:/www/
      - ${CONF_DIR}/php/php.ini/:/usr/local/etc/php/php.ini
      - ${LOG_DIR}/php84:/var/log/php
    environment:
      - TZ:${TZ}
    depends_on:
      - redis
      - mysql
      - postgreSql
    networks: 
      - ycsjnet
  postgreSql:
    image: holovision-postgresql:17.5
    container_name: pgsql17.5
    restart: always
    privileged: false
    volumes:
      - ${CONF_DIR}/postgreSql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ${DATA_DIR}/postgreSql:/var/lib/postgresql/data
      - ${LOG_DIR}/postgreSql:/var/log/postgresql
    ports:
      - ${POSTGRESQL_PORT}:5432
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C.UTF-8"  # 强制UTF-8编码
    networks:
      - ycsjnet
  nginx:
    image: holovision-nginx:1.28.0
    container_name: nginx${NGINX_VERSION}
    restart: always
    privileged: false
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
      - 5173:5173
      - 1998:1998
      - 1999:1999
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/
      - ${NGINX_SSL_CERTIFICATE_DIR}:/etc/nginx/ssl
      - ${LOG_DIR}/nginx${NGINX_VERSION}:/var/log/nginx
      - ${SOURCE_DIR}:/www/
      - ${DABAOENSI_ROOT}:/www/dabaoensi.laravel
      - ${YILIAO_ROOT}:/www/yiliao.laravel
      - ${ZHEGNNIAN_ROOT}:/www/zhengnian.laravel
      - ${MARKET_ROOT}:/www/market.laravel
      - ${PHP84_ROOT}:/www/
    environment:
      - TZ:${TZ}
    depends_on:
      - php82
    networks: 
      - ycsjnet
  awrtc:
    image: holovision-node:20
    container_name: awrtc-1.0
    restart: always
    privileged: false
    working_dir: /app/awrtc
    volumes:
      - ${AWRTC_SERVER_DIR}:/app/awrtc
    ports:
      - ${AWRTC_SERVER_PORT}:3700
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "cd /app/awrtc && npm install && npm run build && export TZ=Asia/Shanghai && npm run start",
      ] 
    networks: 
      - ycsjnet
  skynet:
    image: holovision-skynet:1.7
    container_name: holovision-skynet-1.7
    restart: always
    privileged: false
    environment:
      - GATEWAY=7702
      - REDIS_CONFIG=redis|holovision2023|6379|10|holovision
    ports:
      - 7702:7702
    volumes:
      - ${SOURCE_DIR}/holovision.skynet:/www/holovision.skynet
    command: /skynet/skynet /www/holovision.skynet/config/config_node.lua
    networks:
      - ycsjnet
    depends_on:
      - nginx
  # signalserver:
  #   image: holovision-node:20
  #   container_name: webrtc-signalserver-1.0
  #   restart: always
  #   privileged: false
  #   working_dir: /app/signalserver
  #   volumes:
  #     - ${SIGNALSERVER_DIR}:/app/signalserver
  #   entrypoint:
  #     [
  #       "/bin/bash",
  #       "-c",
  #       "cd /app/signalserver && npm install && export TZ=Asia/Shanghai && npm run serve",
  #     ] 
  #   ports:
  #     - ${SIGNALSERVER_PORT}:3600
  #   networks: 
  #     - ycsjnet
  # dss:
  #   image: holovision-node:20
  #   container_name: dss
  #   restart: always
  #   privileged: false
  #   working_dir: /app/node-dss
  #   volumes:
  #     - ${NODE_DIR}/node-dss:/app/node-dss
  #   entrypoint:
  #     [
  #       "/bin/bash",
  #       "-c",
  #       "cd /app/node-dss && export DEBUG=dss* && npm install && npm start",
  #     ]
  #   ports:
  #     - "3000:3000"
  #   networks: 
  #     - ycsjnet
  # meilisearch:
  #   image: getmeili/meilisearch:latest
  #   container_name: meilisearch_latest
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_MASTER_KEY=masterKey
  #     - MEILI_NO_ANALYTICS=true
  #   volumes:
  #     - ${DATA_DIR}/meilisearch:/var/lib/meilisearch
  #   restart: always
  #   networks:
  #     - ycsjnet
  coturn:
    image: holovision-coturn:1.0
    container_name: coturn-1.0
    restart: always
    privileged: true
    volumes:
      - ${COTURN_CONF_DIR}/turnserver.conf:/etc/turnserver.conf
      - ${COTURN_CONF_DIR}/turnserver.sh:/etc/turnserver.sh
      - ${LOG_DIR}/coturn:/var/log/turnserver
    ports:
      - 3478:3478
      - 3478:3478/udp
    environment:
      - REALM=${COTURN_REALM}
      - USERNAME=${COTURN_USERNAME}
      - PASSWORD=${COTURN_PASSWORD}
      - EXTERNAL_IP=${COTURN_EXTERNAL_IP}
    entrypoint: ['/etc/turnserver.sh']
    command: ['turnserver', '-c', '/etc/turnserver.conf']
    networks:
      - ycsjnet
networks:
  ycsjnet:
    name: 'ycsjnet'
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
        # - subnet: 172.85.0.0/16
